{
 "title": "Meridian DevSecOps Security Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "All DevSecOps Security Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"devsecops-capstone\"}"
    }
   ]
  },
  {
   "title": "AWS Security Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"devsecops-capstone\", cloud=\"aws\"}"
    }
   ]
  },
  {
   "title": "Azure Security Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"devsecops-capstone\", cloud=\"azure\"}"
    }
   ]
  }
 ]
}